name: build-staticOS
on:
  push: 
    branches: 
        - 'master'
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch: 

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-image: 
    name: build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - staticOS
          - staticOS-dx
          - staticOS-dx-virt
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: | 
          # Generate a timestamp for creating an image version history
          TIMESTAMP="$(date +%Y%m%d)"

          build_tags=()

          build_tags+=("${TIMESTAMP}")
          build_tags+=("latest")

          echo "build_tags=${build_tags[*]}" >> $GITHUB_OUTPUT

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ matrix.image_name }}
          tags: |
            ${{ steps.generate-tags.outputs.build_tags }}
          oci: false
          extra-args: |
            --target=${{ matrix.image_name }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

    